const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

const root = document.documentElement;
const setTheme = t => { root.dataset.theme = t; localStorage.setItem('vl-theme', t); document.querySelectorAll('#theme-switch button').forEach(b => b.classList.toggle('active', b.dataset.theme === t)); };
setTheme(localStorage.getItem('vl-theme') || 'system');
document.querySelectorAll('#theme-switch button').forEach(b => b.onclick = () => setTheme(b.dataset.theme));

document.querySelectorAll('.tab').forEach(t => t.onclick = () => {
  document.querySelectorAll('.tab,.panel').forEach(e => e.classList.remove('active'));
  t.classList.add('active');
  $('#panel-' + t.dataset.mode).classList.add('active');
});

const REF = {
  c2pa: ['C2PA Technical Specification 2.1', 'https://c2pa.org/specifications/'],
  iptc: ['IPTC Digital Source Type vocabulary', 'https://cv.iptc.org/newscodes/digitalsourcetype/'],
  synthid: ['Google DeepMind, SynthID', 'https://deepmind.google/technologies/synthid/'],
  prnu: ['Lukáš, Fridrich, Goljan 2006, Digital camera identification from sensor pattern noise', 'https://doi.org/10.1109/TIFS.2006.873602'],
  spec: ['Durall et al. 2020, Watch your Up-Convolution: spectral distortions of CNN generators', 'https://arxiv.org/abs/2003.01826'],
  diff: ['Corvi et al. 2023, On the detection of synthetic images generated by diffusion models', 'https://arxiv.org/abs/2211.00680'],
  jpeg: ['Farid 2009, Exposing digital forgeries from JPEG ghosts', 'https://doi.org/10.1109/TIFS.2008.2012215'],
  ela: ['Krawetz 2007, A picture\'s worth: digital image analysis', 'https://www.hackerfactor.com/papers/bh-usa-07-krawetz-wp.pdf'],
  cfa: ['Popescu & Farid 2005, Exposing forgeries by detecting traces of color interpolation', 'https://doi.org/10.1109/TSP.2005.855406'],
  size: ['Native output sizes of SD/SDXL/DALL·E/Midjourney (multiples of 64)', 'https://arxiv.org/abs/2307.01952'],
  audio: ['ASVspoof challenge, spectral artefacts of synthetic speech', 'https://www.asvspoof.org/'],
  lossy: ['MP3/AAC encoders low-pass at ~16–19 kHz (LAME docs)', 'https://lame.sourceforge.io/'],
  name: ['Filename is user-editable — weak hint only', ''],
  trust: ['C2PA conformance trust list', 'https://github.com/c2pa-org/conformance-public'],
  kobak: ['Kobak et al. 2024, Delving into ChatGPT usage in academic writing through excess vocabulary', 'https://arxiv.org/abs/2406.07016'],
  liangmap: ['Liang et al. 2024, Mapping the increasing use of LLMs in scientific papers', 'https://arxiv.org/abs/2404.01268'],
  gltr: ['Gehrmann et al. 2019, GLTR: statistical detection of generated text', 'https://arxiv.org/abs/1906.04043'],
  sada: ['Sadasivan et al. 2023, Can AI-generated text be reliably detected?', 'https://arxiv.org/abs/2303.11156'],
  bias: ['Liang et al. 2023, GPT detectors are biased against non-native English writers', 'https://arxiv.org/abs/2304.02819'],
  binoc: ['Hans et al. 2024, Spotting LLMs with Binoculars (zero-shot, needs a model)', 'https://arxiv.org/abs/2401.12070'],
  prnu2: ['Chen, Fridrich, Goljan, Lukáš 2008, Determining image origin and integrity using sensor noise', 'https://doi.org/10.1109/TIFS.2007.916285'],
  pce: ['Goljan, Fridrich, Filler 2009, Large scale test of sensor fingerprint camera identification', 'https://doi.org/10.1117/12.805701'],
  cose: ['RFC 9052, CBOR Object Signing and Encryption (COSE)', 'https://www.rfc-editor.org/rfc/rfc9052'],
  qt: ['Kee, Johnson, Farid 2011, Digital image authentication from JPEG headers', 'https://doi.org/10.1109/TIFS.2011.2128309'],
  dq: ['Lukáš & Fridrich 2003, Estimation of primary quantization matrix in double compressed JPEG images', 'https://www.ws.binghamton.edu/fridrich/Research/Doublecompression.pdf'],
  align: ['Bianchi & Piva 2012, Image forgery localization via block-grained analysis of JPEG artifacts', 'https://doi.org/10.1109/TIFS.2012.2187516'],
  temporal: ['Mandelli et al. 2020, Source camera model identification for videos & PRNU across frames', 'https://arxiv.org/abs/2007.07592']
};

const REF_GROUPS = [
  ['Provenance & watermarks', [
    [REF.c2pa, 'C2PA manifest parsing, assertions, content hash', 'JUMBF boxes are parsed and the data hash is recomputed over the file'],
    [REF.cose, 'C2PA signature check', 'COSE_Sign1 signature verified with WebCrypto against the embedded certificate'],
    [REF.iptc, 'IPTC DigitalSourceType', 'Strong: publisher-declared AI or capture source'],
    [REF.synthid, 'SynthID mention', 'Invisible watermark; vendor detector required'],
    [['OpenAI, C2PA in ChatGPT images', 'https://help.openai.com/en/articles/8912793-c2pa-in-chatgpt-images'], 'OpenAI vendor match', 'Explains how metadata is stripped by screenshots/uploads'],
    [['Google, AI image labelling & SynthID Detector', 'https://blog.google/technology/ai/google-synthid-ai-content-detector/'], 'Google vendor match', 'Context for Gemini/Imagen outputs'],
    [REF.name, 'Filename hint', 'Weak: names are user-editable']
  ]],
  ['Image forensics', [
    [REF.prnu, 'Noise σ, noise uniformity, camera make, exposure fields', 'Real sensors leave grain that AI images lack'],
    [REF.cfa, 'CFA / channel noise correlation', 'Bayer demosaicing leaves channel-specific traces'],
    [REF.spec, 'Spectral peak (residual FFT)', 'Upsampling layers create periodic frequency spikes'],
    [REF.diff, 'Kurtosis, flat-area ratio, saturation, video duration', 'Diffusion outputs carry distinctive residual statistics'],
    [['Ojha et al. 2023, Towards universal fake image detectors', 'https://arxiv.org/abs/2302.10174'], 'Overall approach', 'Shows hand-crafted cues generalise poorly — why reliability is shown'],
    [['Liang et al. 2023, GPT detectors are biased against non-native English writers', 'https://arxiv.org/abs/2304.02819'], 'Comparison table', 'Why the text tab does not score AI authorship'],
    [REF.size, 'Dimensions', 'Latent grids yield multiples of 64 and fixed native sizes']
  ]],
  ['Compression & editing', [
    [REF.jpeg, 'JPEG ghost map, 8-px block periodicity, screenshot marker', 'Recompression masks generator traces → lowers reliability'],
    [REF.qt, 'Quantization table origin, IJG quality fit', 'Cameras and software write different tables; a mismatch with EXIF reveals re-saving'],
    [REF.dq, 'Double quantization in DCT histograms', 'A second compression leaves periodic gaps in coefficient histograms'],
    [REF.align, '8×8 grid alignment', 'Coefficients locked to a shifted grid mean crop or shift after compression'],
    [REF.ela, 'Error level analysis map', 'Uneven re-save error reveals edited regions']
  ]],
  ['Audio', [
    [REF.audio, 'Spectral flatness, loudness variation, stereo correlation', 'Synthetic speech/music artefacts'],
    [REF.temporal, 'Video: noise carry-over, texture shimmer, flicker', 'Real sensors repeat a fixed noise pattern from frame to frame; generators re-synthesise it'],
    [REF.lossy, 'Bandwidth cutoff', 'Lossy encoders low-pass the band, erasing evidence'],
    [['Afchar et al. 2024, Detecting music deepfakes is easy but actually hard', 'https://arxiv.org/abs/2405.04181'], 'Overall audio approach', 'Why audio reliability is capped at 60%']
  ]],
  ['Writing check', [
    [REF.kobak, 'Marker vocabulary rate', 'Words such as delve, showcasing and underscores rose sharply after 2022'],
    [REF.liangmap, 'Marker vocabulary rate', 'Population-level estimate; weak on single documents'],
    [REF.gltr, 'Sentence-length burstiness', 'Generated text is more uniform than human text'],
    [REF.sada, 'Reliability caps', 'Paraphrasing defeats detectors, so no style score goes above 85'],
    [REF.bias, 'Length gate, honest note', 'Simple or non-native writing is often flagged wrongly'],
    [REF.binoc, 'Not implemented', 'The strongest zero-shot methods need a language model, which is out of scope']
  ]],
  ['Camera match', [
    [REF.prnu2, 'Fingerprint estimate', 'Maximum-likelihood PRNU estimate from several reference photos'],
    [REF.pce, 'PCE threshold 60', 'False-match rate below 1 in 10⁴ in a test with over 1 million images']
  ]],
  ['Text pattern recognition', [
    [['Unicode TR #18, Regular expressions & \\p{L} classes', 'https://unicode.org/reports/tr18/'], 'Tokenizer', 'Multilingual letter/number detection'],
    [['BIPM, The International System of Units (SI)', 'https://www.bipm.org/en/publications/si-brochure'], 'SI conversion', 'Conversion factors'],
    [['ISO 8601 date and time format', 'https://www.iso.org/iso-8601-date-and-time-format.html'], 'Date normalization', 'Output format YYYY-MM-DD'],
    [['ISO 4217 currency codes', 'https://www.iso.org/iso-4217-currency-codes.html'], 'Currency detection', 'Symbol → code mapping']
  ]]
];
$('#refs-out').innerHTML = REF_GROUPS.map(([g, items]) => '<article class="card"><h3>' + g + '</h3><div class="tablewrap"><table><thead><tr><th>Source</th><th>Used by</th><th>Why it matters</th></tr></thead><tbody>' + items.map(([r, use, why]) => '<tr><td>' + (r[1] ? '<a href="' + r[1] + '" target="_blank" rel="noopener">' + esc(r[0]) + '</a>' : esc(r[0])) + '</td><td>' + esc(use) + '</td><td>' + esc(why) + '</td></tr>').join('') + '</tbody></table></div></article>').join('');

const GEN = [
  ['OpenAI / ChatGPT / DALL·E / Sora', /chatgpt|gpt[-_ ]?4o|gpt[-_ ]?image|dall[-_ ·]?e|openai|sora/i],
  ['Google Gemini / Imagen / Nano Banana / Veo', /gemini|imagen|nano[-_ ]?banana|google[-_ ]?ai|veo[-_ ]?\d?|bard/i],
  ['Midjourney', /midjourney|\bmj[-_ ]?v?\d/i],
  ['Flux / Black Forest Labs', /\bflux|black[-_ ]?forest/i],
  ['Stable Diffusion / SDXL / ComfyUI / A1111', /stable[-_ ]?diffusion|sdxl|\bsd[-_ ]?[123]\b|comfyui|automatic1111|invokeai|fooocus/i],
  ['ByteDance Seedream / Doubao / Jimeng', /seedream|seededit|doubao|jimeng|dreamina/i],
  ['Microsoft Designer / MAI / Copilot', /\bmai[-_ ]?image|\bmai\b|copilot|bing[-_ ]?image|designer/i],
  ['Adobe Firefly', /firefly/i],
  ['xAI Grok / Aurora', /grok|aurora/i],
  ['Ideogram / Leonardo / Recraft / Krea / Playground', /ideogram|leonardo|recraft|krea|playground/i],
  ['Kling / Runway / Pika / Luma / Hailuo', /kling|runway|gen[-_ ]?[34]|pika|luma|dream[-_ ]?machine|hailuo|minimax/i],
  ['Qwen / Hunyuan / Kolors / Wan', /qwen|hunyuan|kolors|\bwan[-_ ]?2/i],
  ['Suno / Udio / ElevenLabs / AIVA', /suno|udio|elevenlabs|aiva|boomy|mubert|stable[-_ ]?audio/i],
  ['Generic AI hint', /\bai[-_ ]?(gen|art|image|generated)|generated|txt2img|img2img|upscayl|topaz/i]
];
const CAMERA = /(Canon|NIKON|SONY|Apple|iPhone|samsung|Google Pixel|Pixel \d|FUJIFILM|OLYMPUS|OM Digital|Panasonic|HUAWEI|Xiaomi|OnePlus|LEICA|Hasselblad|DJI|GoPro|Ricoh|PENTAX|motorola|OPPO|vivo)[^\0\n]{0,28}/;

function sig(name, value, dir, w, why, ref) { return { name, value, dir, w, why, ref }; }

function scanMeta(buf, fname) {
  const n = Math.min(buf.byteLength, 4000000);
  const head = new TextDecoder('latin1').decode(new Uint8Array(buf, 0, n));
  const tail = buf.byteLength > n ? new TextDecoder('latin1').decode(new Uint8Array(buf, buf.byteLength - 400000)) : '';
  const t = head + tail, out = [], info = { strong: false, camera: '', software: '' };
  const u8 = new Uint8Array(buf, 0, 12), hex = [...u8].map(b => b.toString(16).padStart(2, '0')).join('');
  info.format = hex.startsWith('ffd8') ? 'JPEG' : hex.startsWith('89504e47') ? 'PNG' : t.slice(8, 12) === 'WEBP' ? 'WebP' : /ftyp(heic|heix|mif1|avif)/.test(t.slice(0, 32)) ? 'HEIF/AVIF' : t.slice(4, 8) === 'ftyp' ? 'MP4/MOV' : t.startsWith('ID3') || hex.startsWith('fffb') ? 'MP3' : t.startsWith('RIFF') ? 'WAV/RIFF' : t.startsWith('fLaC') ? 'FLAC' : t.startsWith('OggS') ? 'Ogg' : t.startsWith('GIF8') ? 'GIF' : 'Other';
  const c2pa = /c2pa|jumbf|jumb|cbor|contentauth/i.test(t) && /c2pa/i.test(t);
  if (c2pa) {
    info.c2paHeur = true;
    const gen = (t.match(/claim_generator[^\w]{0,6}([\x20-\x7e]{3,60})/) || [])[1] || '';
    const who = GEN.find(g => g[1].test(t.slice(Math.max(0, t.indexOf('c2pa') - 2000), t.indexOf('c2pa') + 60000)));
    const ai = /trainedAlgorithmicMedia|compositeWithTrainedAlgorithmicMedia|c2pa\.created[\s\S]{0,400}algorithm/i.test(t);
    out.push(sig('C2PA (string scan)', (gen || 'manifest present') + (who ? ' · ' + who[0] : ''), ai || who ? 'ai' : 'neutral', ai || who ? 45 : 5, ai ? 'Manifest declares an AI-generated source' : who ? 'Manifest names an AI vendor' : 'Provenance manifest exists; signer not verified', REF.c2pa));
    if (ai || who) { info.strong = true; info.strongHeur = true; }
  }
  const dst = t.match(/digitalsourcetype[^\w]{0,40}[^"<]*?(trainedAlgorithmicMedia|compositeWithTrainedAlgorithmicMedia|algorithmicMedia|compositeSynthetic|digitalCapture|computationalCapture|screenCapture)/i);
  if (dst) {
    const v = dst[1], ai = /algorithmic|Synthetic/i.test(v);
    out.push(sig('IPTC DigitalSourceType', v, ai ? 'ai' : 'real', ai ? 45 : -20, ai ? 'Publisher declared AI origin' : 'Declared capture source', REF.iptc));
    if (ai) info.strong = true;
  }
  const params = t.match(/(parameters|prompt|workflow|Dream|Description|Comment)\0([\x20-\x7e\n]{10,300})/);
  if (params && /steps|sampler|cfg|seed|negative prompt|class_type|model/i.test(params[2])) {
    out.push(sig('Generator text chunk', params[2].slice(0, 120).replace(/\n/g, ' ') + '…', 'ai', 45, 'Diffusion settings embedded (steps/sampler/seed)', REF.diff));
    info.strong = true;
  }
  const soft = ((t.match(/(?:Software|CreatorTool|creator_tool|encoder|TSSE|TENC)[^\x20-\x7e]{0,8}([\x20-\x7e]{3,50})/i) || [])[1] || '').replace(/^[^\w]+|["'>]+$|"/g, '').trim();
  if (soft) {
    info.software = soft.trim();
    const g = GEN.slice(0, -1).find(x => x[1].test(soft));
    out.push(sig('Software / encoder tag', soft.trim(), g ? 'ai' : /photoshop|lightroom|gimp|snapseed|picsart|canva|capture one|darktable|affinity|pixelmator|luminar|dxo/i.test(soft) ? 'proc' : 'neutral', g ? 35 : 0, g ? 'Tag names ' + g[0] : 'Editing/encoding software', REF.c2pa));
    if (g) info.strong = true;
  }
  const cam = t.match(CAMERA);
  if (cam) { info.camera = cam[0].replace(/[^\x20-\x7e]/g, '').trim(); out.push(sig('Camera make/model', info.camera, 'real', -12, 'EXIF names a capture device (can be forged)', REF.prnu)); }
  const exif = t.includes('Exif\0\0');
  if (!exif && !cam && /JPEG|HEIF|WebP|PNG/.test(info.format)) out.push(sig('EXIF block', 'absent', 'proc', 0, 'Missing: typical for screenshots, social media, AI output', REF.c2pa));
  if (/Screenshot|screencapture|screenCapture/i.test(t + fname)) { info.screenshot = true; out.push(sig('Screenshot marker', 'yes', 'proc', 0, 'Pixel traces unreliable after screen capture', REF.jpeg)); }
  const lens = /FocalLength|ExposureTime|FNumber|ISOSpeed/.test(t) || /\x82\x9a|\x82\x9d|\x88\x27/.test(t);
  if (exif && lens) out.push(sig('Exposure fields', 'present', 'real', -8, 'Exposure/ISO/aperture tags exist', REF.prnu));
  const fn = GEN.find(g => g[1].test(fname));
  if (fn) out.push(sig('Filename hint', fname, 'neutral', 0, 'Name contains "' + fname.match(fn[1])[0] + '" → ' + fn[0] + '. User-editable, so it is shown but not scored', REF.name));
  if (/synthid/i.test(t)) out.push(sig('SynthID mention', 'string found', 'ai', 20, 'Text reference only; watermark itself is invisible', REF.synthid));
  return { list: out, info };
}

async function provenance(f, u, meta) {
  let r = null;
  try { r = u ? await C2PA.read(u) : null; if (!r && /MP4|HEIF/.test(meta.info.format)) r = await C2PA.readBmffFile(f); } catch (e) { r = null; }
  if (!r) return;
  const I = meta.info;
  meta.list = meta.list.filter(x => x.name !== 'C2PA (string scan)' && !(r.sourceTypes.length && x.name === 'IPTC DigitalSourceType') && !(x.name === 'Software / encoder tag' && !/^[\w .,()\/-]+$/.test(x.value)));
  if (I.strongHeur) { I.strong = false; I.strongHeur = false; }
  const S = r.sig.status, H = r.hash.status, ok = S === 'valid', tampered = S === 'invalid' || H === 'mismatch';
  const who = GEN.slice(0, -1).find(g => g[1].test(r.generator + ' ' + (r.signer.subject ? (r.signer.subject.O || '') + ' ' + (r.signer.subject.CN || '') : '') + ' ' + r.actions.join(' ')));
  const signer = r.signer.subject ? [r.signer.subject.CN, r.signer.subject.O].filter(Boolean).join(' · ') : '';
  const L = meta.list;
  L.push(sig('C2PA manifest', (r.generator || r.label) + ' · ' + r.manifests + ' manifest' + (r.manifests > 1 ? 's' : '') + (r.ingredients ? ' · ' + r.ingredients + ' ingredient' + (r.ingredients > 1 ? 's' : '') : ''), 'neutral', 0, 'Parsed from JUMBF: ' + r.assertions.length + ' assertions' + (r.manifests > 1 ? '. Several manifests mean the file was edited after the first signature' : ''), REF.c2pa));
  L.push(sig('C2PA signature', S + ' · ' + (r.sig.alg || '?') + (signer ? ' · ' + signer : '') + (r.signer.from ? ' · cert ' + r.signer.from + ' → ' + r.signer.to : ''), S === 'invalid' ? 'proc' : 'neutral', 0, S === 'valid' ? 'Cryptographically valid for the embedded certificate' : S === 'invalid' ? 'Signature does not match the claim: manifest was altered' : 'Could not verify in this browser (' + S + ')', REF.cose));
  L.push(sig('C2PA content hash', H + (r.hash.alg ? ' · ' + r.hash.alg : ''), H === 'mismatch' ? 'proc' : 'neutral', 0, H === 'match' ? 'Pixels and bytes are exactly what was signed' : H === 'mismatch' ? 'File bytes changed after signing' : H === 'unchecked' ? 'Not recomputed (' + (r.hash.alg || '') + ')' : H === 'unconfirmed' ? 'BMFF hash variant not reproduced here; not treated as tampering' : 'No hash assertion', REF.c2pa));
  if (r.actions.length) L.push(sig('C2PA actions', r.actions.slice(0, 6).join(' | '), 'neutral', 0, 'Edit history recorded by the signing tool', REF.c2pa));
  const T = r.trust || {}, tr = T.status === 'trusted';
  if (r.trust) L.push(sig('C2PA certificate chain', T.status + (T.anchor ? ' · ' + T.anchor : T.root ? ' · root ' + T.root : '') + (T.expired ? ' · a certificate has expired' : ''), 'neutral', 0, tr ? 'Chain verified up to an anchor on the official C2PA trust list. Revocation is not checked' : 'Signer identity is not vouched for by the C2PA trust list; the signature still proves the manifest is intact', REF.trust));
  const wAI = tampered ? 15 : ok && tr && H === 'match' ? 50 : ok && tr ? 47 : ok ? 40 : 35;
  if (r.ai) { L.push(sig('C2PA digitalSourceType', r.sourceTypes.join(', '), 'ai', wAI, 'Signed manifest declares AI-generated content' + (tampered ? ', but the manifest or file was altered' : ''), REF.iptc)); I.strong = !tampered; }
  else if (who) { L.push(sig('C2PA AI vendor', who[0], 'ai', Math.round(wAI * .7), 'Manifest generator or signer belongs to an AI vendor', REF.c2pa)); I.strong = !tampered; }
  else if (r.capture) L.push(sig('C2PA digitalSourceType', r.sourceTypes.join(', '), 'real', ok && tr ? -30 : ok ? -20 : -10, ok ? 'Signed manifest declares a camera capture' : 'Declares a capture, but the signature is unverified', REF.iptc));
  I.verified = ok && !tampered; I.tampered = tampered; I.trusted = I.verified && tr;
}

function gray(d, w, h) { const g = new Float32Array(w * h); for (let i = 0; i < w * h; i++) g[i] = d[i * 4] * .299 + d[i * 4 + 1] * .587 + d[i * 4 + 2] * .114; return g; }

function fft(re, im) {
  const n = re.length;
  for (let i = 1, j = 0; i < n; i++) { let b = n >> 1; for (; j & b; b >>= 1) j ^= b; j ^= b; if (i < j) { [re[i], re[j]] = [re[j], re[i]]; [im[i], im[j]] = [im[j], im[i]]; } }
  for (let len = 2; len <= n; len <<= 1) {
    const a = -2 * Math.PI / len, wr = Math.cos(a), wi = Math.sin(a);
    for (let i = 0; i < n; i += len) { let cr = 1, ci = 0; for (let j = 0; j < len / 2; j++) { const k = i + j + len / 2, tr = re[k] * cr - im[k] * ci, ti = re[k] * ci + im[k] * cr; re[k] = re[i + j] - tr; im[k] = im[i + j] - ti; re[i + j] += tr; im[i + j] += ti; const nr = cr * wr - ci * wi; ci = cr * wi + ci * wr; cr = nr; } }
  }
}

function pixelSignals(ctx, w, h, natW, natH) {
  const d = ctx.getImageData(0, 0, w, h).data, g = gray(d, w, h), res = new Float32Array(w * h);
  let n = 0, s1 = 0, s2 = 0, flat = 0, rn = 0, gn = 0, bn = 0, sat = 0, clip = 0;
  for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) {
    const i = y * w + x, r = g[i] - (g[i - 1] + g[i + 1] + g[i - w] + g[i + w]) / 4;
    res[i] = r; s1 += r; s2 += r * r; n++;
    if (Math.abs(g[i + 1] - g[i - 1]) + Math.abs(g[i + w] - g[i - w]) < 2) flat++;
    const p = i * 4;
    rn += Math.abs(d[p] - (d[p - 4] + d[p + 4]) / 2); gn += Math.abs(d[p + 1] - (d[p - 3] + d[p + 5]) / 2); bn += Math.abs(d[p + 2] - (d[p - 2] + d[p + 6]) / 2);
    const mx = Math.max(d[p], d[p + 1], d[p + 2]), mn = Math.min(d[p], d[p + 1], d[p + 2]);
    sat += mx ? (mx - mn) / mx : 0; if (mx >= 254 || mx <= 1) clip++;
  }
  const mean = s1 / n, sd = Math.sqrt(s2 / n - mean * mean);
  let k4 = 0; for (let i = 0; i < res.length; i++) if (res[i]) k4 += ((res[i] - mean) / sd) ** 4; const kurt = k4 / n;
  const bs = 32, vars = [];
  for (let y = 0; y + bs <= h; y += bs) for (let x = 0; x + bs <= w; x += bs) { let a = 0, b = 0; for (let yy = 0; yy < bs; yy++) for (let xx = 0; xx < bs; xx++) { const v = res[(y + yy) * w + x + xx]; a += v; b += v * v; } const m = a / bs / bs; vars.push(b / bs / bs - m * m); }
  const vm = vars.reduce((a, b) => a + b, 0) / vars.length, noiseCV = Math.sqrt(vars.reduce((a, b) => a + (b - vm) ** 2, 0) / vars.length) / (vm + 1e-9);
  const per = new Array(8).fill(0); for (let y = 0; y < h; y++) for (let x = 1; x < w; x++) per[x % 8] += Math.abs(g[y * w + x] - g[y * w + x - 1]);
  const pm = per.reduce((a, b) => a + b) / 8, block = Math.max(...per) / pm;
  const N = 256, ox = Math.max(0, (w - N) >> 1), oy = Math.max(0, (h - N) >> 1), spec = new Float32Array(N);
  if (w >= N && h >= N) {
    for (let y = 0; y < N; y++) { const re = new Float32Array(N), im = new Float32Array(N); for (let x = 0; x < N; x++) re[x] = res[(oy + y) * w + ox + x] * (0.5 - 0.5 * Math.cos(2 * Math.PI * x / N)); fft(re, im); for (let k = 0; k < N; k++) spec[k] += Math.log1p(Math.hypot(re[k], im[k])); }
  }
  let peak = 0, peakAt = 0;
  if (spec[1]) { for (let k = 8; k < N / 2 - 2; k++) { const loc = (spec[k - 3] + spec[k - 2] + spec[k + 2] + spec[k + 3]) / 4, r = spec[k] / (loc + 1e-9); if (r > peak) { peak = r; peakAt = k; } } }
  const chroma = Math.min(rn, gn, bn) / Math.max(rn, gn, bn);
  const hist = new Uint32Array(256), colors = new Set();
  for (let i = 0; i < w * h; i++) { hist[d[i * 4 + 1]]++; if (i % 3 === 0) colors.add((d[i * 4] >> 2) << 12 | (d[i * 4 + 1] >> 2) << 6 | d[i * 4 + 2] >> 2); }
  let lo = 0, hi = 255; while (lo < 255 && !hist[lo]) lo++; while (hi > 0 && !hist[hi]) hi--;
  let gaps = 0; for (let v = lo + 1; v < hi; v++) if (!hist[v] && hist[v - 1] && hist[v + 1]) gaps++;
  const uniq = colors.size / Math.min(262144, Math.ceil(w * h / 3));
  const B = 8, seen = new Map(); let clones = 0, blocks = 0;
  for (let y = 0; y + B <= h; y += 4) for (let x = 0; x + B <= w; x += 4) {
    let key = '', mn = 255, mx = 0;
    for (let yy = 0; yy < B; yy += 2) for (let xx = 0; xx < B; xx += 2) { const v = g[(y + yy) * w + x + xx]; mn = Math.min(mn, v); mx = Math.max(mx, v); key += String.fromCharCode(v >> 3); }
    if (mx - mn < 24) continue; blocks++;
    const p = seen.get(key); if (p && Math.hypot(p[0] - x, p[1] - y) > 24) clones++; else if (!p) seen.set(key, [x, y]);
  }
  const cloneR = blocks ? clones / blocks : 0;
  const M = 256, s2d = new Float32Array(M * M);
  if (w >= M && h >= M) {
    const R = Array.from({ length: M }, (_, y) => { const re = new Float32Array(M), im = new Float32Array(M); for (let x = 0; x < M; x++) re[x] = res[(oy + y) * w + ox + x]; fft(re, im); return [re, im]; });
    for (let x = 0; x < M; x++) { const re = new Float32Array(M), im = new Float32Array(M); for (let y = 0; y < M; y++) { re[y] = R[y][0][x]; im[y] = R[y][1][x]; } fft(re, im); for (let y = 0; y < M; y++) s2d[((y + M / 2) % M) * M + (x + M / 2) % M] = Math.log1p(Math.hypot(re[y], im[y])); }
  }
  const L = [];
  const lowNoise = sd < 1.6, richNoise = sd > 4;
  L.push(sig('Noise residual σ', sd.toFixed(2), lowNoise ? 'ai' : richNoise ? 'real' : 'neutral', lowNoise ? 7 : richNoise ? -8 : 0, lowNoise ? 'Too clean for a sensor at this size' : richNoise ? 'Sensor-like grain present' : 'Mid-range', REF.prnu));
  L.push(sig('Residual kurtosis', kurt.toFixed(1), kurt < 4 ? 'ai' : kurt > 12 ? 'real' : 'neutral', kurt < 4 ? 6 : kurt > 12 ? -5 : 0, kurt < 4 ? 'Near-Gaussian, smoothed noise' : kurt > 12 ? 'Heavy-tailed, natural texture/shot noise' : 'Typical', REF.diff));
  L.push(sig('Noise uniformity (CV)', noiseCV.toFixed(2), noiseCV > 3 ? 'ai' : noiseCV < 1.2 ? 'real' : 'neutral', noiseCV > 3 ? 6 : noiseCV < 1.2 ? -6 : 0, noiseCV > 3 ? 'Detail concentrated, smooth elsewhere' : noiseCV < 1.2 ? 'Even sensor noise across frame' : 'Mixed', REF.prnu));
  L.push(sig('Flat-area ratio', (flat / n * 100).toFixed(0) + '%', flat / n > .7 ? 'ai' : 'neutral', flat / n > .7 ? 4 : 0, flat / n > .7 ? 'Large perfectly smooth zones' : 'Normal range for photos and graphics', REF.diff));
  L.push(sig('Spectral peak (residual FFT)', spec[1] ? peak.toFixed(2) + ' @ f=' + (peakAt / N).toFixed(3) : 'image too small', peak > 1.35 && Math.abs(peakAt / N - .125) > .01 ? 'ai' : peak > 1.35 ? 'proc' : 'neutral', peak > 1.35 && Math.abs(peakAt / N - .125) > .01 ? 12 : 0, peak > 1.35 ? (Math.abs(peakAt / N - .125) <= .01 ? 'Peak at 1/8 = JPEG grid, not generator' : 'Periodic upsampling artefact') : 'No periodic grid', REF.spec));
  L.push(sig('CFA / channel noise correlation', chroma.toFixed(3), chroma > .93 ? 'ai' : chroma < .8 ? 'real' : 'neutral', chroma > .93 ? 5 : chroma < .8 ? -5 : 0, chroma > .93 ? 'Channels equally noisy: no demosaicing trace' : chroma < .8 ? 'Channel-specific noise, Bayer-like' : 'Ambiguous', REF.cfa));
  L.push(sig('8-px block periodicity', block.toFixed(2), block > 1.2 ? 'proc' : 'neutral', 0, block > 1.2 ? 'JPEG (re)compression grid present' : 'No strong grid', REF.jpeg));
  L.push(sig('Mean saturation / clipping', (sat / n * 100).toFixed(0) + '% / ' + (clip / n * 100).toFixed(1) + '%', 'neutral', 0, 'Measured for context only: style and grading drive this more than origin', REF.diff));
  L.push(sig('Histogram comb gaps', gaps + ' empty levels', gaps > 6 ? 'proc' : 'neutral', 0, gaps > 6 ? 'Missing tone levels: contrast/levels edit or bit-depth stretch' : 'Continuous tone distribution', REF.ela));
  L.push(sig('Colour diversity (18-bit)', (uniq * 100).toFixed(1) + '%', 'neutral', 0, uniq < .02 ? 'Very few distinct colours: graphic, palette or heavy quantisation' : 'Measured for context', REF.diff));
  L.push(sig('Cloned regions (copy-move)', clones + ' of ' + blocks + ' textured blocks', cloneR > .01 ? 'proc' : 'neutral', 0, cloneR > .01 ? 'Identical textured blocks far apart: cloning, tiling or repeated patterns' : 'No duplicated texture found', REF.ela));
  const m64 = natW % 64 === 0 && natH % 64 === 0, std = [[1024, 1024], [1024, 1536], [1536, 1024], [1792, 1024], [1024, 1792], [832, 1216], [1216, 832], [896, 1152], [1152, 896], [768, 1344], [1344, 768], [512, 512], [2048, 2048], [1456, 816], [816, 1456]].some(([a, b]) => a === natW && b === natH);
  L.push(sig('Dimensions', natW + '×' + natH, std ? 'ai' : 'neutral', std ? 6 : 0, std ? 'Exact native generator size' : m64 ? 'Multiple of 64 (latent grid)' : 'Not a typical generator size', REF.size));
  return { L, res, sd, s2d: s2d[0] || s2d[1] ? s2d : null, clones };
}

function specMap(s) {
  const M = 256, c = document.createElement('canvas'); c.width = c.height = M; const x = c.getContext('2d'), im = x.createImageData(M, M);
  let mn = Infinity, mx = -Infinity; s.forEach(v => { mn = Math.min(mn, v); mx = Math.max(mx, v); });
  for (let i = 0; i < s.length; i++) { const v = (s[i] - mn) / (mx - mn + 1e-9) * 255; im.data[i * 4] = im.data[i * 4 + 1] = im.data[i * 4 + 2] = v; im.data[i * 4 + 3] = 255; }
  x.putImageData(im, 0, 0); return c.toDataURL('image/png');
}

function maps(img, ctx, w, h, res, sd) {
  const ela = document.createElement('canvas'); ela.width = w; ela.height = h;
  const ec = ela.getContext('2d', { willReadFrequently: true });
  return new Promise(r => {
    const tmp = document.createElement('canvas'); tmp.width = w; tmp.height = h; tmp.getContext('2d').drawImage(img, 0, 0, w, h);
    tmp.toBlob(b => { const im = new Image(); im.onload = () => {
      ec.drawImage(im, 0, 0); const a = ctx.getImageData(0, 0, w, h), c = ec.getImageData(0, 0, w, h);
      for (let i = 0; i < a.data.length; i += 4) for (let k = 0; k < 3; k++) c.data[i + k] = clamp(Math.abs(a.data[i + k] - c.data[i + k]) * 14, 0, 255);
      ec.putImageData(c, 0, 0);
      const nm = document.createElement('canvas'); nm.width = w; nm.height = h; const nc = nm.getContext('2d'), nd = nc.createImageData(w, h);
      for (let i = 0; i < res.length; i++) { const v = clamp(Math.abs(res[i]) / (sd * 3 + 1e-9) * 255, 0, 255); nd.data[i * 4] = nd.data[i * 4 + 1] = nd.data[i * 4 + 2] = v; nd.data[i * 4 + 3] = 255; }
      nc.putImageData(nd, 0, 0); r([ela.toDataURL('image/jpeg', .8), nm.toDataURL('image/jpeg', .8)]);
    }; im.src = URL.createObjectURL(b); }, 'image/jpeg', 0.9);
  });
}

function combine(list, info, cap) {
  const px = list.filter(x => x.px && x.w), ai = px.filter(x => x.w > 0).length, real = px.filter(x => x.w < 0).length;
  let s = 50; list.forEach(x => s += x.w);
  if (!info.strong) s = 50 + (s - 50) * (Math.abs(ai - real) >= 2 ? 1 : .5);
  let rel = 35 + Math.min(30, Math.abs(ai - real) * 8);
  if (info.strong) rel = info.trusted ? 95 : info.verified ? 88 : 80;
  else { if (info.screenshot) rel -= 25; if (info.quality && info.quality < 85) rel -= 12; if (info.double) rel -= 10; if (info.gridLost) rel -= 6; if (info.tampered) rel -= 10; if (cap) rel = Math.min(rel, cap); }
  s = clamp(Math.round(s), info.strong ? 2 : 15, info.strong ? 98 : 85);
  const label = info.strong && s > 70 ? 'Declared / tagged AI' : s >= 68 ? 'Leans AI' : s <= 32 ? 'Leans camera / natural' : 'Inconclusive';
  return { score: s, rel: clamp(Math.round(rel), 10, 95), label, verified: !!info.verified, trusted: !!info.trusted };
}

const DIRL = { ai: '→ AI', real: '→ Camera', proc: '→ Processing', neutral: '· neutral' };
const VCLS = l => l.startsWith('Declared') ? 'tagged' : l === 'Leans AI' ? 'ai' : l.startsWith('Leans camera') ? 'real' : l === 'Error' ? 'error' : 'mixed';
const VNAME = { all: 'All', tagged: 'Tagged AI', ai: 'Leans AI', mixed: 'Inconclusive', real: 'Leans camera', error: 'Errors' };
const entries = [], view = { v: 'all', t: 'all', sort: 'order', q: '' };
const refCell = x => esc(x.why) + (x.ref && x.ref[1] ? '<small><a href="' + x.ref[1] + '" target="_blank" rel="noopener">' + esc(x.ref[0]) + '</a></small>' : '<small>' + esc(x.ref ? x.ref[0] : '') + '</small>');

function checksTable(list) {
  const groups = [['Provenance & metadata', list.filter(x => !x.px && !x.jpg)], ['Compression forensics', list.filter(x => x.jpg)], ['Pixel / signal analysis', list.filter(x => x.px && !x.jpg)]];
  return '<div class="tablewrap"><table><thead><tr><th>Check</th><th>Value</th><th>Points to</th><th>Weight</th><th>Basis / reference</th></tr></thead><tbody>' + groups.filter(g => g[1].length).map(([t, a]) => '<tr class="grp"><td colspan="5">' + t + '</td></tr>' + a.map(x => '<tr><td>' + esc(x.name) + '</td><td>' + esc(x.value) + '</td><td class="to to-' + x.dir + '">' + DIRL[x.dir] + '</td><td>' + (x.w > 0 ? '+' : '') + x.w + '</td><td>' + refCell(x) + '</td></tr>').join('')).join('') + '</tbody></table></div>';
}

function render(file, kind, list, r, extra, thumb) {
  const top = [...list].filter(x => x.w).sort((a, b) => Math.abs(b.w) - Math.abs(a.w)).slice(0, 4);
  const v = VCLS(r.label), type = kind.split(' ')[0];
  const el = document.createElement('details'); el.className = 'fcard v-' + v;
  const th = thumb ? '<img class="thumb" src="' + thumb + '" alt="">' : '<span class="thumb glyph">' + (type === 'Audio' ? '♪' : type === 'Video' ? '▶' : '!') + '</span>';
  el.innerHTML = '<summary>' + th + '<span class="fmeta"><b>' + esc(file.name) + '</b><small>' + esc(kind) + ' · ' + (file.size / 1048576).toFixed(2) + ' MB' + (top[0] ? ' · ' + esc(top[0].name) + ' ' + DIRL[top[0].dir] : '') + '</small></span><span class="vpill">' + esc(r.label) + '</span><span class="fscore"><b>' + r.score + '%</b><small>reliability ' + r.rel + '%</small><span class="mini"><i style="width:' + r.score + '%"></i></span></span></summary><div class="fbody"><p class="honest">' + (r.label === 'Error' ? 'File could not be decoded.' : /Declared/.test(r.label) ? 'Based on an embedded provenance tag' + (r.trusted ? ' with a valid signature from a C2PA-trusted signer' : r.verified ? ' with a valid signature (signer not on the C2PA trust list)' : '') + '. Tags can be stripped, but they are not guesses.' : 'Statistical estimate from measured signals, not proof. Without a provenance tag the score stays between 15 and 85.') + '</p>' + (list.length ? '<h4>Main drivers</h4><ul class="drivers">' + (top.map(x => '<li><b>' + DIRL[x.dir] + '</b> ' + esc(x.name) + ': ' + esc(x.why) + '</li>').join('') || '<li>No decisive signal</li>') + '</ul>' : '') + (extra || '') + (list.length ? '<details class="checks" open><summary>All ' + list.length + ' checks</summary>' + checksTable(list) + '</details>' : '') + '</div>';
  entries.push({ name: file.name, type, v, r, el, idx: entries.length, top: top[0] ? top[0].name + ' ' + DIRL[top[0].dir] : '' });
  $('#media-out').append(el); drawDash();
  return el;
}

function drawDash() {
  $('#batch-dash').hidden = !entries.length;
  const c = { all: entries.length, tagged: 0, ai: 0, mixed: 0, real: 0, error: 0 };
  entries.forEach(e => c[e.v]++);
  const ok = entries.filter(e => e.v !== 'error'), avgRel = ok.length ? Math.round(ok.reduce((a, e) => a + e.r.rel, 0) / ok.length) : 0;
  $('#dash-stats').innerHTML = '<div class="dist">' + ['tagged', 'ai', 'mixed', 'real', 'error'].filter(k => c[k]).map(k => '<i class="d-' + k + '" style="flex:' + c[k] + '" title="' + VNAME[k] + ': ' + c[k] + '"></i>').join('') + '</div><div class="stat-row"><span><b>' + c.all + '</b> files</span><span><b>' + (c.tagged + c.ai) + '</b> lean AI</span><span><b>' + c.mixed + '</b> inconclusive</span><span><b>' + c.real + '</b> lean camera</span><span><b>' + avgRel + '%</b> avg reliability</span></div>';
  $('#verdict-chips').innerHTML = Object.keys(VNAME).filter(k => k === 'all' || c[k]).map(k => '<button class="chip d-' + k + (view.v === k ? ' active' : '') + '" data-v="' + k + '">' + VNAME[k] + ' <b>' + c[k] + '</b></button>').join('');
  applyView();
}

function applyView() {
  const q = view.q.toLowerCase(), S = { order: (a, b) => a.idx - b.idx, high: (a, b) => b.r.score - a.r.score, low: (a, b) => a.r.score - b.r.score, rel: (a, b) => b.r.rel - a.r.rel, name: (a, b) => a.name.localeCompare(b.name), type: (a, b) => a.type.localeCompare(b.type) || b.r.score - a.r.score };
  let shown = 0;
  [...entries].sort(S[view.sort]).forEach(e => { const vis = (view.v === 'all' || e.v === view.v) && (view.t === 'all' || e.type === view.t) && (!q || e.name.toLowerCase().includes(q)); e.el.hidden = !vis; if (vis) shown++; $('#media-out').append(e.el); });
  $('#dash-count').textContent = shown + ' of ' + entries.length + ' shown';
}

$('#verdict-chips').onclick = e => { const b = e.target.closest('.chip'); if (b) { view.v = b.dataset.v; drawDash(); } };
$('#type-filter').onchange = e => { view.t = e.target.value; applyView(); };
$('#sort-by').onchange = e => { view.sort = e.target.value; applyView(); };
$('#batch-search').oninput = e => { view.q = e.target.value; applyView(); };
$('#expand-all').onclick = () => entries.forEach(e => { if (!e.el.hidden) e.el.open = true; });
$('#collapse-all').onclick = () => entries.forEach(e => e.el.open = false);
$('#batch-clear').onclick = () => { entries.splice(0).forEach(e => e.el.remove()); view.v = 'all'; drawDash(); $('#media-progress').textContent = ''; };
$('#batch-csv').onclick = () => { const q = v => '"' + String(v ?? '').replace(/"/g, '""') + '"', rows = [['File', 'Type', 'Score', 'Verdict', 'Reliability', 'Top signal'], ...entries.map(e => [e.name, e.type, e.r.score, e.r.label, e.r.rel, e.top])], a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([rows.map(r => r.map(q).join(',')).join('\n')], { type: 'text/csv' })); a.download = 'veritas-batch.csv'; a.click(); };
const fit = (w, h, m) => { const k = Math.min(1, m / Math.max(w, h)); return [Math.round(w * k), Math.round(h * k)]; };

async function doImage(f) {
  const buf = await f.arrayBuffer(), u = new Uint8Array(buf), meta = scanMeta(buf, f.name);
  await provenance(f, u, meta);
  const img = new Image(); img.src = URL.createObjectURL(f); await img.decode();
  let jp = { L: [], maps: '' };
  if (meta.info.format === 'JPEG') {
    let src = img; try { src = await createImageBitmap(f, { imageOrientation: 'none' }); } catch (e) {}
    try { jp = await JPG.analyze(src, u, meta.info); jp.L.forEach(x => x.jpg = true); } catch (e) {}
  }
  const [w, h] = fit(img.naturalWidth, img.naturalHeight, 1024);
  const c = document.createElement('canvas'); c.width = w; c.height = h;
  const ctx = c.getContext('2d', { willReadFrequently: true }); ctx.drawImage(img, 0, 0, w, h);
  const px = pixelSignals(ctx, w, h, img.naturalWidth, img.naturalHeight); px.L.forEach(x => x.px = true);
  if (meta.info.sub && meta.info.sub !== '4:4:4') px.L.forEach(x => { if (x.name.startsWith('CFA')) Object.assign(x, { dir: 'neutral', w: 0, why: 'Not scored: ' + meta.info.sub + ' chroma subsampling erases demosaicing traces' }); });
  const editor = meta.list.some(x => x.name === 'Software / encoder tag' && x.dir === 'proc');
  if (editor) px.L.forEach(x => { if (x.name === 'Noise residual σ' && x.w > 0) Object.assign(x, { dir: 'neutral', w: 0, why: 'Not scored: the file passed through editing software, which usually applies noise reduction' }); });
  if (img.naturalWidth > w * 1.5) px.L.forEach(x => { if (x.name === 'Noise residual σ' && x.w > 0) Object.assign(x, { dir: 'neutral', w: 0, why: 'Not scored: analysed at ' + w + 'px, and downscaling averages sensor noise away' }); });
  const list = [...meta.list, ...jp.L, ...px.L], r = combine(list, meta.info);
  const [ela, nm] = await maps(img, ctx, w, h, px.res, px.sd);
  const sp = px.s2d ? '<figure><img src="' + specMap(px.s2d) + '" alt="spectrum"><figcaption>2D residual spectrum: bright dots off-centre = periodic upsampling grid</figcaption></figure>' : '';
  render(f, 'Image · ' + meta.info.format, list, r, '<div class="maps"><figure><img src="' + img.src + '" alt="original"><figcaption>Original</figcaption></figure><figure><img src="' + ela + '" alt="ELA"><figcaption>Error level analysis: uneven bright patches = edits or pasted regions</figcaption></figure><figure><img src="' + nm + '" alt="noise"><figcaption>Noise residual: camera = even grain; AI = smooth with detail only on edges</figcaption></figure>' + sp + jp.maps + '</div>', img.src);
}

async function doVideo(f) {
  const meta = scanMeta(await f.slice(0, 4000000).arrayBuffer(), f.name);
  const v = document.createElement('video'); v.muted = true; v.playsInline = true; v.preload = 'auto'; v.src = URL.createObjectURL(f);
  await new Promise((ok, no) => { v.onloadeddata = ok; v.onerror = no; });
  const [w, h] = fit(v.videoWidth, v.videoHeight, 512);
  const c = document.createElement('canvas'); c.width = w; c.height = h;
  const ctx = c.getContext('2d', { willReadFrequently: true });
  await provenance(f, null, meta);
  const N = 8, fr = [], resid = [], shimmer = [], lum = []; let prev = null, diffs = [];
  const seek = t => new Promise(r => { v.onseeked = r; v.currentTime = Math.min(v.duration - .01, t); });
  const grab = () => { ctx.drawImage(v, 0, 0, w, h); return gray(ctx.getImageData(0, 0, w, h).data, w, h); };
  const residual = g => { const r = new Float32Array(g.length); for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) { const i = y * w + x; r[i] = g[i] - (g[i - 1] + g[i + 1] + g[i - w] + g[i + w]) / 4; } return r; };
  for (let i = 0; i < N; i++) {
    const t = v.duration * (i + .5) / N;
    await seek(t); const g = grab(); fr.push(pixelSignals(ctx, w, h, v.videoWidth, v.videoHeight));
    const r1 = residual(g); resid.push(r1);
    let lm = 0; for (let k = 0; k < g.length; k += 5) lm += g[k]; lum.push(lm / (g.length / 5));
    await seek(t + 1 / 30); const g2 = grab(), r2 = residual(g2);
    let a = 0, b = 0, n = 0; for (let k = w + 1; k < g.length - w - 1; k += 3) if (Math.abs(g[k] - g2[k]) < 1.5 && Math.abs(r1[k]) > 1) { a += Math.abs(r1[k] - r2[k]); b += Math.abs(r1[k]); n++; }
    if (n > 500) shimmer.push(a / b);
    if (prev) { let s = 0; for (let k = 0; k < g.length; k += 7) s += Math.abs(g[k] - prev[k]); diffs.push(s / (g.length / 7)); } prev = g;
  }
  const fpn = [];
  resid.forEach((r, i) => { let ab = 0, aa = 0, bb = 0; for (let k = 0; k < r.length; k += 2) { let o = 0; resid.forEach((q, j) => { if (j !== i) o += q[k]; }); o /= N - 1; ab += r[k] * o; aa += r[k] * r[k]; bb += o * o; } fpn.push(ab / Math.sqrt(aa * bb + 1e-9)); });
  const fp = fpn.sort((a, b) => a - b)[N >> 1];
  const med = a => a.length ? [...a].sort((p, q) => p - q)[a.length >> 1] : null, sh = med(shimmer);
  const lmM = lum.reduce((a, b) => a + b) / N, flick = Math.sqrt(lum.reduce((a, b) => a + (b - lmM) ** 2, 0) / N);
  const px = fr[0].L.map((x, j) => { const ws = fr.map(f => f.L[j].w), aw = Math.round(ws.reduce((a, b) => a + b) / N); return { ...x, value: fr.map(f => f.L[j].value).slice(0, 3).join(' | ') + '…', w: aw, dir: aw > 0 ? 'ai' : aw < 0 ? 'real' : x.dir, px: true }; }).filter(x => x.name !== 'Dimensions' && x.name !== 'Mean saturation / clipping');
  const sds = fr.map(f => f.sd), m = sds.reduce((a, b) => a + b) / N, cv = Math.sqrt(sds.reduce((a, b) => a + (b - m) ** 2, 0) / N) / (m + 1e-9);
  px.push({ ...sig('Noise stability across frames', cv.toFixed(3), cv < .04 ? 'ai' : 'neutral', cv < .04 ? 4 : 0, cv < .04 ? 'Noise level nearly frozen between shots' : 'Varies like real footage', REF.prnu), px: true });
  const dm = diffs.reduce((a, b) => a + b, 0) / diffs.length;
  px.push({ ...sig('Fixed-pattern noise carry-over', fp.toFixed(3), fp > .06 ? 'real' : 'neutral', fp > .06 ? -5 : 0, fp > .06 ? 'The same noise pattern repeats across distant frames: consistent with a physical sensor' : 'No stable sensor pattern found. Generators show this, but so do heavy compression and moving cameras, so it is not scored', REF.temporal), px: true });
  if (sh !== null) px.push({ ...sig('Texture shimmer (static areas, 1/30 s apart)', sh.toFixed(2), 'neutral', 0, sh > 1.2 ? 'Fine texture changes a lot between adjacent frames in still areas: re-synthesis or strong denoising' : 'Fine texture is stable where nothing moves', REF.temporal), px: true });
  px.push({ ...sig('Brightness flicker across samples', flick.toFixed(1) + ' levels', 'neutral', 0, 'Context: cuts and lighting changes dominate this value', REF.temporal), px: true });
  px.push({ ...sig('Duration / motion', v.duration.toFixed(1) + 's · Δ' + dm.toFixed(1), 'neutral', 0, 'Measured for context only: clip length is not evidence of origin', REF.diff), px: true });
  const list = [...meta.list, ...px], r = combine(list, meta.info, 45);
  render(f, 'Video · ' + v.videoWidth + '×' + v.videoHeight, list, r, '<div class="maps"><figure><video src="' + v.src + '" controls playsinline muted></video><figcaption>Preview</figcaption></figure></div>', c.toDataURL('image/jpeg', .7));
}

async function doAudio(f) {
  const buf = await f.arrayBuffer(), meta = scanMeta(buf, f.name);
  await provenance(f, new Uint8Array(buf), meta);
  const ac = new (window.AudioContext || window.webkitAudioContext)();
  const ab = await ac.decodeAudioData(buf.slice(0)); ac.close();
  const x = ab.getChannelData(0), y = ab.numberOfChannels > 1 ? ab.getChannelData(1) : null, sr = ab.sampleRate, N = 4096;
  const hops = Math.min(160, Math.floor(x.length / N)), step = Math.floor(x.length / hops), avg = new Float32Array(N / 2), flats = [], rms = [];
  for (let k = 0; k < hops; k++) {
    const o = k * step, re = new Float32Array(N), im = new Float32Array(N); let e = 0;
    for (let n = 0; n < N; n++) { const s = x[o + n] || 0; e += s * s; re[n] = s * (0.5 - 0.5 * Math.cos(2 * Math.PI * n / N)); }
    fft(re, im); let lg = 0, ar = 0;
    for (let b = 1; b < N / 2; b++) { const m = Math.hypot(re[b], im[b]); avg[b] += m; lg += Math.log(m + 1e-12); ar += m; }
    flats.push(Math.exp(lg / (N / 2 - 1)) / (ar / (N / 2 - 1) + 1e-12)); rms.push(Math.sqrt(e / N));
  }
  const db = [...avg].map(v => 20 * Math.log10(v / hops + 1e-12)), mx = Math.max(...db.slice(5));
  let cut = 0; for (let b = N / 2 - 1; b > 5; b--) if (db[b] > mx - 60) { cut = b * sr / N; break; }
  let hf = 0, hc = 0; for (let b = Math.floor(16000 / sr * N); b < Math.floor(Math.min(20000, cut) / sr * N); b++) { hf += db[b]; hc++; }
  const med = a => [...a].sort((p, q) => p - q)[a.length >> 1], fl = med(flats);
  const rm = rms.reduce((a, b) => a + b) / hops, dyn = Math.sqrt(rms.reduce((a, b) => a + (b - rm) ** 2, 0) / hops) / (rm + 1e-9);
  const peak = Math.max(...rms), crest = 20 * Math.log10(peak / (rm + 1e-9));
  let corr = null; if (y) { let a = 0, b = 0, c = 0; for (let i = 0; i < x.length; i += 50) { a += x[i] * y[i]; b += x[i] ** 2; c += y[i] ** 2; } corr = a / Math.sqrt(b * c + 1e-12); }
  const L = [];
  L.push(sig('Bandwidth cutoff', Math.round(cut) + ' Hz', cut < 16500 ? 'proc' : 'neutral', 0, cut < 16500 ? 'Lossy low-pass: evidence weakened' : 'Full-band', REF.lossy));
  const shelf = cut > 15000 && cut < 16500 && /MP3|Other|MP4/.test(meta.info.format) === false;
  if (shelf) L.push(sig('16 kHz shelf on lossless file', 'yes', 'ai', 8, 'Lossless container with lossy-like band limit: often generator output', REF.audio));
  L.push(sig('Spectral flatness', fl.toFixed(3), fl > .35 ? 'ai' : fl < .08 ? 'real' : 'neutral', fl > .35 ? 5 : fl < .08 ? -3 : 0, fl > .35 ? 'Smeared, noise-like spectrum (vocoder trait)' : 'Tonal structure', REF.audio));
  L.push(sig('Loudness variation', dyn.toFixed(2), dyn < .22 ? 'ai' : dyn > .8 ? 'real' : 'neutral', dyn < .22 ? 6 : dyn > .8 ? -6 : 0, dyn < .22 ? 'Unusually constant energy' : dyn > .8 ? 'Natural dynamics' : 'Typical mastered music', REF.audio));
  L.push(sig('Crest factor', crest.toFixed(1) + ' dB', 'neutral', 0, 'Context only: loudness-war masters also score low', REF.audio));
  if (corr !== null) L.push(sig('Stereo L/R correlation', corr.toFixed(3), corr > .985 ? 'ai' : 'neutral', corr > .985 ? 4 : 0, corr > .985 ? 'Near-mono stereo image' : 'Real stereo spread', REF.audio));
  L.push(sig('Format', meta.info.format + ' · ' + sr + ' Hz · ' + ab.numberOfChannels + 'ch · ' + ab.duration.toFixed(1) + 's', 'neutral', 0, 'Measured for context only', REF.audio));
  L.forEach(v => v.px = true);
  const list = [...meta.list, ...L], r = combine(list, meta.info, 60);
  render(f, 'Audio · ' + meta.info.format, list, r, '<audio controls src="' + URL.createObjectURL(f) + '" style="width:100%;margin-top:14px"></audio>');
}

async function handleFiles(files) {
  const arr = [...files]; let i = 0;
  for (const f of arr) {
    $('#media-progress').textContent = 'Analyzing ' + (++i) + ' / ' + arr.length + ': ' + f.name;
    try {
      const t = f.type || '', ext = f.name.split('.').pop().toLowerCase();
      if (t.startsWith('image/') || /heic|avif|webp|png|jpe?g|gif|bmp/.test(ext)) await doImage(f);
      else if (t.startsWith('video/') || /mp4|mov|webm|mkv/.test(ext)) await doVideo(f);
      else if (t.startsWith('audio/') || /mp3|wav|flac|ogg|m4a|aac|opus/.test(ext)) await doAudio(f);
      else if (t.startsWith('text/') || /txt|csv|tsv|log|md|json|html?/.test(ext)) { $('#text-input').value += (await f.text()) + '\n'; extractText(); $('#media-progress').textContent = f.name + ' sent to Text → Table'; }
      else throw new Error('unsupported type');
    } catch (e) { render(f, 'Unreadable · ' + (f.type || 'unknown'), [], { score: 0, rel: 0, label: 'Error' }, '<p>Could not decode in this browser (' + esc(e.message || 'format') + ').</p>'); }
  }
  $('#media-progress').textContent = arr.length + ' file(s) done';
}
$('#media-input').onchange = e => handleFiles(e.target.files);
const dz = $('#drop-zone');
['dragenter', 'dragover'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.add('over'); }));
['dragleave', 'drop'].forEach(ev => dz.addEventListener(ev, e => { e.preventDefault(); dz.classList.remove('over'); }));
dz.addEventListener('drop', e => handleFiles(e.dataTransfer.files));

